Repository SamBaekSu/ProQ-Noti, pull requests merged in 2025-07, with the labels that each got.

#80 feat: fcm 도입 미완
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/firebase-messaging-sw.js
  client/public/sw.js
  client/src/app/Pwa.tsx
  client/src/app/api/register/route.ts
  client/src/app/api/subscribe/route.ts
  client/src/app/page.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/constant/db.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/usePlayer.ts
  client/src/lib/firebase.ts
  client/src/utils/device.ts
  client/src/utils/supabase/supabase.d.ts
  client/yarn.lock
  supabase/.gitignore
  supabase/.temp/cli-latest
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/types.ts
  supabase/functions/push/.npmrc
  supabase/functions/push/deno.json
  supabase/functions/push/index.ts
  supabase/functions/update-players/index.ts
Labels: ✨ Feat, 🖥️FE

#82 fix: push 오류 수정
  client/public/firebase-messaging-sw.js
  client/src/app/Pwa.tsx
  client/src/app/provider.tsx
  client/src/lib/firebase.ts
Labels: 🐞 BugFix, ✨ Feat

#83 v0.0.13
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/firebase-messaging-sw.js
  client/public/sw.js
  client/src/app/Pwa.tsx
  client/src/app/api/register/route.ts
  client/src/app/api/subscribe/route.ts
  client/src/app/page.tsx
  client/src/app/provider.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/constant/db.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/usePlayer.ts
  client/src/lib/firebase.ts
  client/src/utils/device.ts
  client/src/utils/supabase/supabase.d.ts
  client/yarn.lock
  supabase/.gitignore
  supabase/.temp/cli-latest
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/types.ts
  supabase/functions/push/.npmrc
  supabase/functions/push/deno.json
  supabase/functions/push/index.ts
  supabase/functions/update-players/index.ts
Labels: 🌏 Deploy

#85 v0.0.13 fix
  client/public/sw.js
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/lib/firebase.ts
Labels: 🐞 BugFix, 🌏 Deploy

#92 fix: google 로그인 테이블 미삽입 에러 수정
  client/src/app/api/auth/callback/google/route.ts
Labels: 🐞 BugFix

#96 v0.0.15 fix
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
Labels: 🌏 Deploy

#100 fix: 알림 2번 오는 오류 수정
  client/public/firebase-messaging-sw.js
  supabase/functions/push/index.ts
Labels: 🐞 BugFix

#109 feat: 토큰 재발행
  client/public/firebase-messaging-sw.js
  client/public/sw.js
  client/src/app/api/register/route.ts
  client/src/app/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
  client/src/lib/firebase.ts
  supabase/.temp/cli-latest
Labels: 🐞 BugFix, ✨ Feat, 🖥️FE

#111 design:ui 크기 조절
  client/src/app/page.tsx
  client/src/components/Layout.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
Labels: 🖥️FE, 🎨 Html&Css

#115 design:뱃지 파일 변경
  client/public/android-192x192.png
  client/src/components/dropdown.tsx
Labels: 📃 Docs, 🖥️FE

#116 v0.0.22
  client/public/android-192x192.png
  client/src/components/dropdown.tsx
Labels: 🌏 Deploy
