Repository SamBaekSu/ProQ-Noti, pull requests merged in 2025-04, with the labels that each got.

#59 Perf: 실시간 선수 온라인 여부 확인
  client/src/app/api/subscribe/route.ts
  client/src/app/page.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/Layout.tsx
  client/src/components/SubscribeSkeleton.tsx
  client/src/hooks/usePlayer.ts
  client/src/utils/supabase/supabase.d.ts
  client/supabase/.temp/cli-latest
  client/supabase/config.toml
  client/supabase/functions/_shared/types.ts
  client/supabase/functions/update-players/index.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/supabaseClient.ts
  supabase/functions/_shared/types.ts
  supabase/functions/update-players/.npmrc
  supabase/functions/update-players/deno.json
  supabase/functions/update-players/index.ts
Labels: 🖥️FE, 🔨 Refactor

#60 v0.0.8
  client/src/app/api/subscribe/route.ts
  client/src/app/page.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/Layout.tsx
  client/src/components/SubscribeSkeleton.tsx
  client/src/hooks/usePlayer.ts
  client/src/utils/supabase/supabase.d.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/functions/_shared/types.ts
  supabase/functions/update-players/index.ts
Labels: 🌏 Deploy

#61 Fix: 로그인 기능 에러 수정
  client/package.json
  client/src/app/api/auth/callback/google/route.ts
  client/src/app/api/auth/callback/kakao/route.ts
  client/src/app/layout.tsx
  client/src/app/layoutRouter.tsx
  client/src/app/provider.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/subscribeList.tsx
  client/src/store/AuthProvider.tsx
  client/src/utils/supabase/client.ts
  client/yarn.lock
Labels: 🐞 BugFix

#67 Feat: 계정 테이블 분리 및 실시간 새로고침 수정, 구독 insert
  .vscode/extensions.json
  client/package-lock.json
  client/package.json
  client/public/sw.js
  client/src/app/Pwa.tsx
  client/src/app/_notification/InstallPrompt.tsx
  client/src/app/_notification/PushNotificationManager.tsx
  client/src/app/_notification/Pwa.tsx
  client/src/app/_notification/actions.ts
  client/src/app/api/subscribe/route.ts
  client/src/app/layout.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/constant/db.ts
  client/src/hooks/usePlayer.ts
  client/src/store/AuthProvider.tsx
  client/src/store/authSlice.ts
  client/src/types/subscribe.ts
  client/src/utils/hooks/userAuth.ts
  client/src/utils/supabase/supabase.d.ts
  client/yarn.lock
  supabase/.temp/cli-latest
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/types.ts
  supabase/functions/update-players/index.ts
Labels: ✨ Feat, 🖥️FE

#68 v0.0.9
  .vscode/extensions.json
  client/package-lock.json
  client/package.json
  client/public/sw.js
  client/src/app/Pwa.tsx
  client/src/app/_notification/InstallPrompt.tsx
  client/src/app/_notification/PushNotificationManager.tsx
  client/src/app/_notification/Pwa.tsx
  client/src/app/_notification/actions.ts
  client/src/app/api/auth/callback/google/route.ts
  client/src/app/api/auth/callback/kakao/route.ts
  client/src/app/api/subscribe/route.ts
  client/src/app/layout.tsx
  client/src/app/layoutRouter.tsx
  client/src/app/provider.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/constant/db.ts
  client/src/hooks/usePlayer.ts
  client/src/store/AuthProvider.tsx
  client/src/store/authSlice.ts
  client/src/types/subscribe.ts
  client/src/utils/hooks/userAuth.ts
  client/src/utils/supabase/client.ts
  client/src/utils/supabase/supabase.d.ts
  client/yarn.lock
  supabase/.temp/cli-latest
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/types.ts
  supabase/functions/update-players/index.ts
Labels: 🌏 Deploy

#69 fix: 더미데이터 수정
  client/src/app/myPage/page.tsx
Labels: 🐞 BugFix

#65 Feat: 라이브 게임중인 선수들의 룬, 스펠, 챔피언 api 호출 적용
  client/src/app/api/live-game/route.ts
  client/src/components/ChampionImage.tsx
  client/src/components/IngameBox.tsx
  client/src/components/RuneImage.tsx
  client/src/components/SpellImages.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/hooks/useLiveGameBySummonerId.ts
  client/src/hooks/useOutsideClick.ts
  client/yarn.lock
Labels: ✨ Feat, 🖥️FE

#70 Fix: 병합 오류 수정
  client/src/components/IngameBox.tsx
  client/src/components/dropdown.tsx
Labels: 🐞 BugFix
