Repository SamBaekSu/ProQ-Noti, pull requests merged in 2025-03, with the labels that each got.

#17 Feature: 로그인 페이지 마크업
  client/package.json
  client/src/app/login/page.tsx
  client/yarn.lock
Labels: 🎨 Html&Css

#18 Feat: 구독 리스트 화면 생성
  client/.prettierrc
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/app/assets/fonts/KCC-Ganpan.woff
  client/src/app/assets/fonts/Pretendard-Black.woff
  client/src/app/assets/fonts/Pretendard-Bold.woff
  client/src/app/assets/fonts/Pretendard-ExtraBold.woff
  client/src/app/assets/fonts/Pretendard-ExtraLight.woff
  client/src/app/assets/fonts/Pretendard-Light.woff
  client/src/app/assets/fonts/Pretendard-Medium.woff
  client/src/app/assets/fonts/Pretendard-Regular.woff
  client/src/app/assets/fonts/Pretendard-SemiBold.woff
  client/src/app/assets/fonts/Pretendard-Thin.woff
  client/src/app/assets/icons/live.svg
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/app/subscribe/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/subscribeList.tsx
  client/src/types/index.ts
  client/src/types/subscribe.ts
  client/src/utils/hooks/useOutsideClick.ts
  client/tailwind.config.ts
  client/tsconfig.json
  client/yarn.lock
Labels: ✨ Feat, 🖥️FE, 🎨 Html&Css

#20 feat: 메인페이지 마크업
  client/src/app/page.tsx
  client/yarn.lock
Labels: 🎨 Html&Css

#25 Feature/UI update
  client/next.config.js
  client/src/app/layout.tsx
  client/src/app/layoutWrapper.tsx
  client/src/components/IngameBox.tsx
  client/tailwind.config.ts
  client/yarn.lock
Labels: ✨ Feat, 🖥️FE, 🎨 Html&Css

#27 feat: 드롭다운 생성
  client/src/app/_notification/PushNotificationManager.tsx
  client/src/app/_notification/actions.ts
  client/src/app/layoutWrapper.tsx
  client/src/components/dropdown.tsx
Labels: ✨ Feat, 🖥️FE, 🎨 Html&Css

#30 Feature: 전체 레이아웃 수정
  client/src/app/assets/icons/Menu.svg
  client/src/app/assets/icons/arrowBack.svg
  client/src/app/layout.tsx
  client/src/app/layoutWrapper.tsx
  client/src/app/page.tsx
  client/src/app/subscribe/page.tsx
  client/src/components/Layout.tsx
  client/yarn.lock
Labels: 🎨 Html&Css

#33 feat: 메인페이지 반응형 적용 및 중복코드 컴포넌트 적용, (팀 목록만)폰트 적용
  client/src/app/layoutWrapper.tsx
  client/src/app/login/page.tsx
  client/src/app/page.tsx
  client/src/components/Layout.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
  client/src/components/dropdown.tsx
Labels: ✨ Feat, 🔨 Refactor

#39 Bugfix: layout
  client/src/app/layout.tsx
  client/src/app/layoutRouter.tsx
  client/src/app/layoutWrapper.tsx
  client/src/app/myPage/page.tsx
  client/src/app/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/Layout.tsx
Labels: ✨ Feat, 🎨 Html&Css

#42 feat: 메인페이지 반응 수정
  client/src/app/page.tsx
  client/src/components/Layout.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
Labels: 🔨 Refactor

#46 Feat: supabase 연결해서 데이터 가져오기
  client/src/app/api/subscribe/route.ts
  client/src/app/api/team/route.ts
  client/src/app/page.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
  client/src/components/subscribeList.tsx
  client/src/constant/db.ts
  client/src/types/index.ts
  client/src/types/subscribe.ts
  client/src/types/teamList.ts
  client/src/utils/supabase/client.ts
  client/src/utils/supabase/supabase.d.ts
Labels: ✨ Feat, 🖥️FE

#50 v0.0.7
  client/components.json
  client/next.config.js
  client/package.json
  client/src/app/_notification/PushNotificationManager.tsx
  client/src/app/_notification/Pwa.tsx
  client/src/app/_notification/actions.ts
  client/src/app/api/auth/callback/google/route.ts
  client/src/app/api/auth/callback/kakao/route.ts
  client/src/app/api/subscribe/route.ts
  client/src/app/api/team/route.ts
  client/src/app/dashboard/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/layoutRouter.tsx
  client/src/app/login/page.tsx
  client/src/app/myPage/page.tsx
  client/src/app/page.tsx
  client/src/app/provider.tsx
  client/src/app/subscribe/[team]/page.tsx
  client/src/app/subscribe/page.tsx
  client/src/components/IngameBox.tsx
  client/src/components/Layout.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/constant/db.ts
  client/src/hooks/use-toast.ts
  client/src/lib/utils.ts
  client/src/store/AuthProvider.tsx
  client/src/store/authSlice.ts
  client/src/store/store.ts
  client/src/types/index.ts
  client/src/types/subscribe.ts
  client/src/types/teamList.ts
  client/src/types/user.ts
  client/src/utils/supabase/client.ts
  client/src/utils/supabase/supabase.d.ts
  client/tailwind.config.ts
  client/yarn.lock
Labels: 🌏 Deploy

#55 refactor: move supabase folder to project root
  supabase/.temp/cli-latest
  supabase/config.toml
  supabase/functions/_shared/constants.ts
  supabase/functions/_shared/supabaseClient.ts
  supabase/functions/_shared/types.ts
  supabase/functions/update-players/.npmrc
  supabase/functions/update-players/deno.json
  supabase/functions/update-players/index.ts
Labels: Chore, ⚙️ conf, 🌏 Deploy
