Repository SamBaekSu/ProQ-Noti, pull requests merged in 2025-05, with the labels that each got.

#71 Feat: IngameBox 룬, 스펠, 챔피언 이미지 불러오기 추가
  client/src/app/api/live-game/route.ts
  client/src/components/ChampionImage.tsx
  client/src/components/IngameBox.tsx
  client/src/components/RuneImage.tsx
  client/src/components/SpellImages.tsx
  client/src/utils/hooks/lol.ts
Labels: ✨ Feat, 🖥️FE

#72 v0.0.10
  client/src/app/api/live-game/route.ts
  client/src/components/ChampionImage.tsx
  client/src/components/IngameBox.tsx
  client/src/components/RuneImage.tsx
  client/src/components/SpellImages.tsx
  client/src/components/TeamCard.tsx
  client/src/components/TeamGrid.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/hooks/useLiveGameBySummonerId.ts
  client/src/hooks/useOutsideClick.ts
  client/src/utils/hooks/lol.ts
  client/yarn.lock
Labels: 🌏 Deploy

#77 Refactoring: ingame box
  client/src/app/test/page.tsx
  client/src/components/ChampionImage.tsx
  client/src/components/IngameBox.tsx
  client/src/components/RuneImages.tsx
  client/src/components/SpellImages.tsx
  client/src/components/dropdown.tsx
  client/src/components/subscribeList.tsx
  client/src/components/ui/toaster.tsx
  client/src/hooks/lol.ts
  client/src/hooks/useLiveGameBySummonerId.ts
  client/src/hooks/usePlayer.ts
  client/src/hooks/useToast.ts
  client/src/hooks/userAuth.ts
  client/src/store/AuthProvider.tsx
  client/src/types/index.ts
  client/src/types/liveGame.ts
  client/src/utils/hooks/lol.ts
Labels: 🖥️FE, 🔨 Refactor
